"""DREAM deal-persistence package. Import the public surface from here."""
from .deal_store import (
    DealStore,
    SQLiteDealStore,
    DealRecord,
    DealNotFound,
    VersionConflict,
    get_deal_store,
    open_sqlite,
    default_db_path,
)
from .user_store import (
    SQLiteUserStore,
    UserRecord,
    UserNotFound,
    UserExists,
    get_user_store,
)
from .crm_store import (
    CRMStore,
    SQLiteCRMStore,
    ContactRecord,
    ItemRecord,
    LinkRecord,
    ContactNotFound,
    ItemNotFound,
    get_crm_store,
    CONTACT_KINDS,
    CONTACT_ROLES,
    ITEM_KINDS,
    TASK_STATUSES,
    LINKABLE_KINDS,
)

__all__ = [
    "DealStore",
    "SQLiteDealStore",
    "DealRecord",
    "DealNotFound",
    "VersionConflict",
    "get_deal_store",
    "open_sqlite",
    "default_db_path",
    "SQLiteUserStore",
    "UserRecord",
    "UserNotFound",
    "UserExists",
    "get_user_store",
    "CRMStore",
    "SQLiteCRMStore",
    "ContactRecord",
    "ItemRecord",
    "LinkRecord",
    "ContactNotFound",
    "ItemNotFound",
    "get_crm_store",
    "CONTACT_KINDS",
    "CONTACT_ROLES",
    "ITEM_KINDS",
    "TASK_STATUSES",
    "LINKABLE_KINDS",
]
